## Logging
logging:
  level:
    ROOT: INFO
    com.sparqr: INFO
    org.springframework: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    org.zalando.logbook: ${LOGBOOK_LOG_LEVEL:TRACE}

## Application server
server:
  port: ${SERVER_PORT:80}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/hal+json,application/problem+json

## Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,prometheus,flyway,httptrace,info
      cors:
        allowed-origins: "*"
        allowed-methods: GET
    jmx:
      exposure:
        exclude=*:
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
    flyway:
      enabled: true
    httptrace:
      enabled: true
    info:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  info:
    git:
      enabled: true
      mode: simple

## Spring configuration
spring:
  application:
    name: sparqr-be
  ## Default datasource -db
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-test-query: SELECT 1
      jdbc-url: ${spring.datasource.url}
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: be-data
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
  flyway:
    enabled: false

feign:
  httpclient:
    enabled: true
    connection-timeout: 5000
  client:
    compression:
      response:
        enabled: true
      request:
        enabled: true

## Global configurations
common:
  date-format: "yyyy-MM-dd"
  datetime-format: "yyyy-MM-dd HH:mm:ss"

app:
  cx:
    client:
      iam-services:
        url: ${IAM_SERVICES_URL:http://localhost:8001}
      gig-services:
        url: ${GIG_SERVICES_URL:http://localhost:8002}
      booking-services:
        url: ${BOOKING_SERVICES_URL:http://localhost:8003}
    aws:
      xray:
        enabled: ${AWS_XRAY_TRACING_ENABLED:false}
      feign:
        enabld: ${FEIGN_ENABLED:false}
